name: Compostable
version: '${version}'
main: io.github.derec4.compostable.Compostable
api-version: "1.18"
authors:
  - DerexXD
description: "Survival friendly plugin that makes more things usable for the composter block, like rotten flesh and fish!"
website: "https://github.com/DereC4"

